version: '3.4'

services:
  scheduleservice:
    image: ${DOCKER_REGISTRY-}scheduleservice
    build:
      context: .
      dockerfile: ScheduleService/Dockerfile

  ticketservice:
    image: ${DOCKER_REGISTRY-}ticketservice
    build:
      context: .
      dockerfile: TicketService/Dockerfile

